### ISSUE TITLE
Version constraint too tight

### ISSUE THREAD

**Issue by wilr** [sajansharmanz/silverstripe-bootstrap-carousel#4]
Version constraint is set to "3.4.0" which means 3.4.x-dev or 3.4.1 is unsupported. Could that constraint be loosened?

**Comment by sajansharmanz** [comment]
Hi there,

Have been using this on SS 4.0 so yes it can. I am unable to make it to my PC for a few days, more than happy to merge a pull request if you are able to fix this

Thanks
Sajan

**Comment by wilr** [comment]
👍  Thanks Sajan

**Comment by sajansharmanz** [comment]
Pleasure :)
