### ISSUE TITLE
img with 0 width and 0 height

### ISSUE THREAD

**Issue by SqualaDesign** [sajansharmanz/silverstripe-bootstrap-carousel#6]
Hi, I install your modules, everything ok but when I'm looking on the website I have the img into a carousel with 0px width and 0px height.
Do you know why?
<img width="1680" alt="screen shot 2017-07-03 at 4 16 59 pm" src="https://user-images.githubusercontent.com/8541984/27777943-64f17102-600b-11e7-8032-93f9e65579c7.png">

**Comment by sajansharmanz** [comment]
Hi there,

This would be because the first item is not getting _active_ class with the JQuery added in my module. Make sure you have the JQuery script tag at the bottom of your body and it should work fine. I have tested this just now as well and replicated the issue

**Comment by SqualaDesign** [comment]
Hi, I checked and jquery is there 
<img width="985" alt="screen shot 2017-07-03 at 5 22 23 pm" src="https://user-images.githubusercontent.com/8541984/27779061-5f0f14ca-6014-11e7-884b-fd660a58df15.png">
Do I have to change the version?

**Comment by sajansharmanz** [comment]
Hi there,

I have tested this using all 3 versions of JQuery from the google hosted libraries and it has worked using all of them.

Please confirm the following:
1. You have added the following to between your _head_ tag
 `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">`

2. You have added the following before your the closing _body_ tag
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>`

3. You have added the following line in the template file that you wish to display the carousel on
`<% include CarouselImages %>`

4. You have enabled a carousel on the page from the admin section and added images

As long as you have done the above it should work. It would be hard to figure out what is causing your issue without seeing your actual files from here. This module has been used many times without issue - therefore we can rule out any problems with the module - there must be something in the setup of the module in your project causing the issue. Please review your setup of this module.

Thanks,
Sajan

**Comment by SqualaDesign** [comment]
I did everything and I update jQuery to 3 but I have this error
<img width="678" alt="screen shot 2017-07-03 at 5 45 31 pm" src="https://user-images.githubusercontent.com/8541984/27779498-82f59fe6-6017-11e7-948d-dd8d8eacdb9c.png">
and this is the link: http://costruzioni.squaladesign.it/

**Comment by sajansharmanz** [comment]
Hi there,

can you please add the following just before your closing _body_ tag and after the JQuery script

```
<script type="text/javascript">
	$(document).ready(function() {
		$('#carousel').find('.item').first().addClass('active');
		$('#carousel').find('.indicator-pos').first().addClass('active');
	});
</script>
```

**Comment by sajansharmanz** [comment]
The other way is to add your script tags in your _head_ tags and this should work

**Comment by SqualaDesign** [comment]
I insert jquery into the head...it's ok now
thanks
