### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by SqualaDesign** [sajansharmanz/silverstripe-bootstrap-carousel#7]
I try to install in SilverStripe 4.0.1 but I have that error:
Fatal error: Class 'DataExtension' not found in /home/dferoliregionale/public_html/carousel/code/extensions/CarouselExtension.php on line 3

**Comment by sajansharmanz** [comment]
Hi there,

Apologies for the late reply.

Modules have not yet been upgraded to work with SS4 entirely yet. I look to get around to do this at some point but am currently very busy with other work. If you would like you can do this and submit a pull request that i can merge if the matter is of urgency

Cheers,

**Comment by sajansharmanz** [comment]
Hi there,

This module has now been upgraded to SilverStripe 4 and is all working

If you have any more issues please let me know

Cheers,
